"use client";
import { useState, useCallback } from "react";
import * as XLSX from "xlsx";
const SB = "https://yihnycafoaemoambrdfd.supabase.co";
const AK = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaG55Y2Fmb2FlbW9hbWJyZGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4NDU2NTQsImV4cCI6MjA5NjQyMTY1NH0.hZVtBbnPEwd_aInDrMiXrLTHSIWlWNimPRfAOC9O66A";
const RED = "#CC2229";
function pDate(v){if(!v)return null;if(v instanceof Date)return v.toISOString().split("T")[0];if(typeof v==="number")return new Date(Math.round((v-25569)*86400*1000)).toISOString().split("T")[0];return String(v).split(" ")[0]||null;}
function iUrl(id){return id?"https://app.i-list.gr/appFol/appDetails/estateDetails/estateDetails.aspx?id="+id:null;}
function mUrl(a,ar){return"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent([a,ar].filter(Boolean).join(", ")+", Greece");}
function thumb(p){return p&&!p.includes("no-photo")?"https://app.i-list.gr"+p:null;}
function pRow(row){const flag=String(row[0]??row[1]??"").trim();const id=String(row[2]??"").trim();if(!id||id==="ID"||id==="undefined")return null;const addr=row[11]&&row[11]!=="***"?String(row[11]).trim():null;const rating=parseInt((flag.match(/(d)/)||[])[1]||"0");return{ilist_id:id,ilist_url:iUrl(id),thumbnail_url:thumb(String(row[4]??"")),maps_url:mUrl(addr,String(row[8]??"")),approval_flag:flag||null,meeting_rating:rating||null,add_to_meeting:rating>=4,transaction_type:String(row[5]??"").startsWith("Ενοικίαση")?"rental":"sale",property_type:String(row[7]??"").trim()||null,status:String(row[25]??"available").trim(),area:String(row[8]??"").trim()||null,sub_area:String(row[9]??"").trim()||null,postal_code:String(row[10]??"").trim()||null,address:addr,price:parseFloat(row[14])||null,price_per_sqm:parseFloat(row[16])||null,sqm:parseFloat(row[15])||null,bedrooms:parseInt(row[17])||null,floor:String(row[18]??"").trim()||null,year_built:parseInt(row[19])||null,mandate_start:pDate(row[20]),mandate_end:pDate(row[21]),source:String(row[22]??"").trim()||null,agent_name:String(row[23]??"").trim()||null,updated_at:new Date().toISOString()};}
async function ups(rows){const r=await fetch(SB+"/rest/v1/properties",{method:"POST",headers:{apikey:AK,Authorization:"Bearer "+AK,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"},body:JSON.stringify(rows)});if(!r.ok)throw new Error(await r.text());}
export default function ImportPage(){const[file,setFile]=useState(null);const[rows,setRows]=useState([]);const[stats,setStats]=useState(null);const[step,setStep]=useState("idle");const[err,setErr]=useState(null);const[pct,setPct]=useState(0);const[fil,setFil]=useState("all");const load=useCallback((f)=>{if(!f)return;setFile(f);setStep("loading");const rd=new FileReader();rd.onload=(e)=>{try{const wb=XLSX.read(e.target.result,{type:"array"});const d=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:""});const p=d.slice(1).map(pRow).filter(Boolean);setRows(p);setStats({total:p.length,meeting:p.filter(r=>r.add_to_meeting).length,sale:p.filter(r=>r.transaction_type==="sale").length,rental:p.filter(r=>r.transaction_type==="rental").length});setStep("preview");}catch(e){setErr(e.message);setStep("error");}};rd.readAsArrayBuffer(f);},[]);const doImp=async()=>{setStep("importing");setPct(0);try{for(let i=0;i<rows.length;i+=50){await ups(rows.slice(i,i+50));setPct(Math.round(((i+Math.min(50,rows.length-i))/rows.length)*100));}setStep("done");}catch(e){setErr(e.message);setStep("error");}};const reset=()=>{setFile(null);setRows([]);setStats(null);setStep("idle");setErr(null);setPct(0);setFil("all");};const vis=fil==="meeting"?rows.filter(r=>r.add_to_meeting):fil==="sale"?rows.filter(r=>r.transaction_type==="sale"):fil==="rental"?rows.filter(r=>r.transaction_type==="rental"):rows;
return(<div style={{fontFamily:"system-ui",maxWidth:900,margin:"0 auto",padding:"32px 24px",color:"#1a1a1a"}}><div style={{marginBottom:28}}><div style={{fontSize:11,fontWeight:600,letterSpacing:".12em",color:RED,textTransform:"uppercase",marginBottom:6}}>KWAC Performance OS</div><h1 style={{margin:0,fontSize:24,fontWeight:600}}>Εισαγωγή ακινήτων iList</h1><p style={{margin:"6px 0 0",color:"#666",fontSize:13}}>Ανέβασε το GridExport.xlsx. Ακίνητα ≥4★ μπαίνουν αυτόματα στο Meeting Dashboard.</p></div>
{(step==="idle"||step==="loading")&&<div onDrop={e=>{e.preventDefault();load(e.dataTransfer.files[0]);}} onDragOver={e=>e.preventDefault()} onClick={()=>document.getElementById("fi").click()} style={{border:"2px dashed #ddd",borderRadius:12,padding:"56px 32px",textAlign:"center",cursor:"pointer",background:"#fafafa"}}><div style={{fontSize:36,marginBottom:12}}>📊</div><div style={{fontWeight:600,marginBottom:6}}>{step==="loading"?"Φόρτωση...":"Σύρε το Excel ή κάνε κλικ"}</div><div style={{color:"#999",fontSize:13}}>GridExport .xlsx από το iList</div><input id="fi" type="file" accept=".xlsx,.xls" style={{display:"none"}} onChange={e=>load(e.target.files[0])}/></div>}
{step==="preview"&&stats&&<div><div style={{display:"flex",gap:10,marginBottom:20,flexWrap:"wrap"}}>{[["Σύνολο",stats.total,"all"],["Meeting ≥4★",stats.meeting,"meeting"],["Πωλήσεις",stats.sale,"sale"],["Ενοικιάσεις",stats.rental,"rental"]].map(([l,v,k])=><div key={k} onClick={()=>setFil(k)} style={{flex:1,minWidth:110,padding:"14px 18px",borderRadius:10,cursor:"pointer",background:fil===k?RED:"#f5f5f5",color:fil===k?"#fff":"#333"}}><div style={{fontSize:26,fontWeight:700}}>{v}</div><div style={{fontSize:11,opacity:.8,marginTop:2}}>{l}</div></div>)}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div style={{fontSize:13,color:"#666"}}>📄 <strong>{file?.name}</strong></div><button onClick={reset} style={{background:"none",border:"none",color:"#999",cursor:"pointer"}}>✕</button></div><div style={{border:"1px solid #eee",borderRadius:10,overflow:"hidden",marginBottom:20}}><div style={{overflowX:"auto",maxHeight:340,overflowY:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#f9f9f9"}}>{["iList","Τύπος","Περιοχή","Τ.μ.","Τιμή","Agent","★","Status"].map(h=><th key={h} style={{padding:"9px 12px",textAlign:"left",fontWeight:600,fontSize:10,textTransform:"uppercase",letterSpacing:".06em",color:"#888",borderBottom:"1px solid #eee"}}>{h}</th>)}</tr></thead><tbody>{vis.slice(0,100).map((r,i)=><tr key={i} style={{borderBottom:"1px solid #f5f5f5",background:r.add_to_meeting?"#fff8f8":"white"}}><td style={{padding:"8px 12px"}}><a href={r.ilist_url} target="_blank" rel="noreferrer" style={{color:RED,textDecoration:"none",fontFamily:"monospace",fontSize:11}}>{r.ilist_id}</a></td><td style={{padding:"8px 12px"}}>{r.property_type}</td><td style={{padding:"8px 12px"}}><a href={r.maps_url} target="_blank" rel="noreferrer" style={{color:"#0066cc",textDecoration:"none"}}>{r.area}{r.sub_area?"/"+r.sub_area:""}</a></td><td style={{padding:"8px 12px"}}>{r.sqm?r.sqm+" τμ":"—"}</td><td style={{padding:"8px 12px",fontWeight:500}}>{r.price?"€"+r.price.toLocaleString("el-GR"):"—"}</td><td style={{padding:"8px 12px",color:"#555",fontSize:11}}>{r.agent_name||"—"}</td><td style={{padding:"8px 12px",textAlign:"center",color:r.add_to_meeting?RED:"#ddd"}}>{r.add_to_meeting?"★★★★":"—"}</td><td style={{padding:"8px 12px"}}><span style={{fontSize:10,padding:"2px 7px",borderRadius:20,background:r.status==="Διαθέσιμο"?"#dcfce7":"#f3f4f6",color:r.status==="Διαθέσιμο"?"#166534":"#555"}}>{r.status}</span></td></tr>)}</tbody></table></div></div><div style={{display:"flex",gap:10,justifyContent:"flex-end"}}><button onClick={reset} style={{padding:"11px 22px",borderRadius:8,border:"1px solid #ddd",background:"white",cursor:"pointer",fontSize:13}}>Ακύρωση</button><button onClick={doImp} style={{padding:"11px 24px",borderRadius:8,border:"none",background:RED,color:"white",cursor:"pointer",fontSize:13,fontWeight:600}}>Εισαγωγή {stats.total} ακινήτων →</button></div></div>}
{step==="importing"&&<div style={{textAlign:"center",padding:"56px 32px"}}><div style={{fontWeight:600,marginBottom:20}}>Εισαγωγή... {pct}%</div><div style={{background:"#f5f5f5",borderRadius:999,height:8,maxWidth:400,margin:"0 auto"}}><div style={{height:"100%",background:RED,borderRadius:999,width:pct+"%",transition:"width .3s"}}/></div><div style={{marginTop:12,color:"#999",fontSize:13}}>{Math.round(pct*rows.length/100)} / {rows.length}</div></div>}
{step==="done"&&<div style={{textAlign:"center",padding:"56px 32px"}}><div style={{fontSize:44,marginBottom:14}}>✅</div><h2 style={{margin:"0 0 8px"}}>Ολοκληρώθηκε</h2><p style={{color:"#666",marginBottom:6}}><strong>{stats?.total}</strong> ακίνητα εισήχθησαν</p><p style={{color:RED,fontWeight:600,marginBottom:28}}>{stats?.meeting} ακίνητα ≥4★ → Meeting Dashboard</p><div style={{display:"flex",gap:10,justifyContent:"center"}}><button onClick={reset} style={{padding:"11px 22px",borderRadius:8,border:"1px solid #ddd",background:"white",cursor:"pointer",fontSize:13}}>Νέα εισαγωγή</button><a href="/dashboard" style={{padding:"11px 22px",borderRadius:8,background:RED,color:"white",textDecoration:"none",fontSize:13,fontWeight:600}}>Dashboard →</a></div></div>}
{step==="error"&&<div style={{textAlign:"center",padding:"56px 32px"}}><div style={{fontSize:44,marginBottom:14}}>⚠️</div><h2 style={{margin:"0 0 8px"}}>Σφάλμα</h2><p style={{color:"#666",fontFamily:"monospace",fontSize:12,marginBottom:24}}>{err}</p><button onClick={reset} style={{padding:"11px 22px",borderRadius:8,border:"1px solid #ddd",background:"white",cursor:"pointer",fontSize:13}}>Δοκίμασε ξανά</button></div>}
</div>);}